// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317021311_AddCreatedByToGameplayContent")]
    partial class AddCreatedByToGameplayContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("campaign_name");

                    b.HasKey("Id");

                    b.ToTable("campaigns");
                });

            modelBuilder.Entity("Api.Models.CampaignUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usr_cmpg");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("id_campaign");

                    b.Property<bool>("IsDm")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_dm");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.ToTable("campaign_users");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Backstory")
                        .HasColumnType("longtext")
                        .HasColumnName("backstory");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("character_name");

                    b.Property<string>("Characteristics")
                        .HasColumnType("longtext")
                        .HasColumnName("characteristics");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int")
                        .HasColumnName("current_hp");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("int")
                        .HasColumnName("current_mp");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int")
                        .HasColumnName("max_hp");

                    b.Property<int>("MaxMp")
                        .HasColumnType("int")
                        .HasColumnName("max_mp");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("stats");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("RaceId");

                    b.ToTable("character_sheets");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CurrencyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("conversion_rate");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("currency_values");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("Api.Models.Gameplay.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("items_inv");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AC")
                        .HasColumnType("int")
                        .HasColumnName("ac");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Damage")
                        .HasColumnType("longtext")
                        .HasColumnName("damage");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext")
                        .HasColumnName("modifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Api.Models.Gameplay.KnownSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterSheetId")
                        .HasColumnType("int")
                        .HasColumnName("character_sheet_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.HasIndex("SkillId");

                    b.ToTable("known_skills");
                });

            modelBuilder.Entity("Api.Models.Gameplay.KnownSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterSheetId")
                        .HasColumnType("int")
                        .HasColumnName("character_sheet_id");

                    b.Property<int>("SpellId")
                        .HasColumnType("int")
                        .HasColumnName("spell_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.HasIndex("SpellId");

                    b.ToTable("known_spells");
                });

            modelBuilder.Entity("Api.Models.Gameplay.MapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("campaign_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("MapImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("maps");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("modifiers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("races");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("effect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("effect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("spells");
                });

            modelBuilder.Entity("Api.Models.Gameplay.SystemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterSheetId")
                        .HasColumnType("int")
                        .HasColumnName("character_sheet_model_id");

                    b.Property<int?>("ClassesId")
                        .HasColumnType("int")
                        .HasColumnName("classes_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<int>("ItemsId")
                        .HasColumnType("int")
                        .HasColumnName("items_id");

                    b.Property<int>("MapsId")
                        .HasColumnType("int")
                        .HasColumnName("maps_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("RacesId")
                        .HasColumnType("int")
                        .HasColumnName("races_id");

                    b.Property<int?>("SkillTreeId")
                        .HasColumnType("int")
                        .HasColumnName("skill_tree_id");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int")
                        .HasColumnName("skills_id");

                    b.Property<int>("SpellsId")
                        .HasColumnType("int")
                        .HasColumnName("spells_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("systems");
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Api.Models.CampaignUser", b =>
                {
                    b.HasOne("Api.Models.Campaign", "Campaign")
                        .WithMany("CampaignMembers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheet", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("Api.Models.Gameplay.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId");

                    b.Navigation("Inventory");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CurrencyValue", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Currency", "Currency")
                        .WithMany("Values")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Api.Models.Gameplay.InventoryItem", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Item", b =>
                {
                    b.HasOne("Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.KnownSkill", b =>
                {
                    b.HasOne("Api.Models.Gameplay.CharacterSheet", "CharacterSheet")
                        .WithMany("KnownSkills")
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSheet");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Api.Models.Gameplay.KnownSpell", b =>
                {
                    b.HasOne("Api.Models.Gameplay.CharacterSheet", "CharacterSheet")
                        .WithMany("KnownSpells")
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSheet");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Api.Models.Gameplay.MapModel", b =>
                {
                    b.HasOne("Api.Models.Campaign", "Campaign")
                        .WithMany("Maps")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Race", b =>
                {
                    b.HasOne("Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Skill", b =>
                {
                    b.HasOne("Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Spell", b =>
                {
                    b.HasOne("Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.SystemModel", b =>
                {
                    b.HasOne("Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Campaign", b =>
                {
                    b.Navigation("CampaignMembers");

                    b.Navigation("Maps");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheet", b =>
                {
                    b.Navigation("KnownSkills");

                    b.Navigation("KnownSpells");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Currency", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
