// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423025934_AddCampaignIdToCharacterSheet")]
    partial class AddCampaignIdToCharacterSheet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("campaign_name");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("invite_code");

                    b.Property<int>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("system_id");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("campaigns");
                });

            modelBuilder.Entity("Api.Models.CampaignUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usr_cmpg");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("id_campaign");

                    b.Property<bool>("IsDm")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_dm");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.ToTable("campaign_users");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("character_name");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("values");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaceId");

                    b.ToTable("character_sheets");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Definitions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("definitions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("character_sheet_models");
                });

            modelBuilder.Entity("Api.Models.Gameplay.ClassModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("int")
                        .HasColumnName("class_group_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Definitions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("definitions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CurrencyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("conversion_rate");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("currency_values");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("class_groups");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.ItemGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("item_groups");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.MapGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("map_groups");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.RaceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("race_groups");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.SkillGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("skill_groups");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.SpellGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("spell_groups");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("Api.Models.Gameplay.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("items_inv");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Definitions")
                        .HasColumnType("longtext")
                        .HasColumnName("definitions");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("ItemGroupId")
                        .HasColumnType("int")
                        .HasColumnName("item_group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ItemGroupId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Api.Models.Gameplay.KnownSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterSheetId")
                        .HasColumnType("int")
                        .HasColumnName("character_sheet_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.HasIndex("SkillId");

                    b.ToTable("known_skills");
                });

            modelBuilder.Entity("Api.Models.Gameplay.KnownSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterSheetId")
                        .HasColumnType("int")
                        .HasColumnName("character_sheet_id");

                    b.Property<int>("SpellId")
                        .HasColumnType("int")
                        .HasColumnName("spell_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.HasIndex("SpellId");

                    b.ToTable("known_spells");
                });

            modelBuilder.Entity("Api.Models.Gameplay.MapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int?>("MapGroupId")
                        .HasColumnType("int")
                        .HasColumnName("map_group_id");

                    b.Property<string>("MapImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MapGroupId");

                    b.ToTable("maps");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("modifiers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("RaceGroupId")
                        .HasColumnType("int")
                        .HasColumnName("race_group_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RaceGroupId");

                    b.ToTable("races");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("effect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("SkillGroupId")
                        .HasColumnType("int")
                        .HasColumnName("skill_group_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SkillGroupId");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("effect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("SpellGroupId")
                        .HasColumnType("int")
                        .HasColumnName("spell_group_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SpellGroupId");

                    b.ToTable("spells");
                });

            modelBuilder.Entity("Api.Models.Gameplay.SystemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterSheetId")
                        .HasColumnType("int")
                        .HasColumnName("character_sheet_model_id");

                    b.Property<int?>("ClassesId")
                        .HasColumnType("int")
                        .HasColumnName("classes_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("SkillTreeId")
                        .HasColumnType("int")
                        .HasColumnName("skill_tree_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("systems");
                });

            modelBuilder.Entity("Api.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Api.Models.User.UserVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("user_verifications");
                });

            modelBuilder.Entity("SystemItemGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("SystemId", "ItemGroupId")
                        .IsUnique();

                    b.ToTable("SystemItemGroups");
                });

            modelBuilder.Entity("SystemMapGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MapGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MapGroupId");

                    b.HasIndex("SystemId", "MapGroupId")
                        .IsUnique();

                    b.ToTable("SystemMapGroups");
                });

            modelBuilder.Entity("SystemRaceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RaceGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceGroupId");

                    b.HasIndex("SystemId", "RaceGroupId")
                        .IsUnique();

                    b.ToTable("SystemRaceGroups");
                });

            modelBuilder.Entity("SystemSkillGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SkillGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillGroupId");

                    b.HasIndex("SystemId", "SkillGroupId")
                        .IsUnique();

                    b.ToTable("SystemSkillGroups");
                });

            modelBuilder.Entity("SystemSpellGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SpellGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellGroupId");

                    b.HasIndex("SystemId", "SpellGroupId")
                        .IsUnique();

                    b.ToTable("SystemSpellGroups");
                });

            modelBuilder.Entity("Api.Models.Campaign", b =>
                {
                    b.HasOne("Api.Models.Gameplay.SystemModel", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("Api.Models.CampaignUser", b =>
                {
                    b.HasOne("Api.Models.Campaign", "Campaign")
                        .WithMany("CampaignMembers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheet", b =>
                {
                    b.HasOne("Api.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.CharacterSheetModel", "Model")
                        .WithMany("Instances")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.User.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId");

                    b.Navigation("Campaign");

                    b.Navigation("Model");

                    b.Navigation("Player");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheetModel", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.ClassModel", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Groups.ClassGroup", "Group")
                        .WithMany("Classes")
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Currency", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CurrencyValue", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Currency", "Currency")
                        .WithMany("Values")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.ClassGroup", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.ItemGroup", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.MapGroup", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.RaceGroup", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.SkillGroup", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.SpellGroup", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Models.Gameplay.InventoryItem", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Item", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Groups.ItemGroup", "Group")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Api.Models.Gameplay.KnownSkill", b =>
                {
                    b.HasOne("Api.Models.Gameplay.CharacterSheet", "CharacterSheet")
                        .WithMany("KnownSkills")
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSheet");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Api.Models.Gameplay.KnownSpell", b =>
                {
                    b.HasOne("Api.Models.Gameplay.CharacterSheet", "CharacterSheet")
                        .WithMany("KnownSpells")
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSheet");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Api.Models.Gameplay.MapModel", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Groups.MapGroup", "MapGroup")
                        .WithMany("Maps")
                        .HasForeignKey("MapGroupId");

                    b.Navigation("Creator");

                    b.Navigation("MapGroup");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Race", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Groups.RaceGroup", "Group")
                        .WithMany("Races")
                        .HasForeignKey("RaceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Skill", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Groups.SkillGroup", "Group")
                        .WithMany("Skills")
                        .HasForeignKey("SkillGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Spell", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.Groups.SpellGroup", "Group")
                        .WithMany("Spells")
                        .HasForeignKey("SpellGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Api.Models.Gameplay.SystemModel", b =>
                {
                    b.HasOne("Api.Models.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SystemItemGroup", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Groups.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.SystemModel", "System")
                        .WithMany("SystemItems")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemGroup");

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemMapGroup", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Groups.MapGroup", "MapGroup")
                        .WithMany()
                        .HasForeignKey("MapGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.SystemModel", "System")
                        .WithMany("SystemMaps")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapGroup");

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemRaceGroup", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Groups.RaceGroup", "RaceGroup")
                        .WithMany()
                        .HasForeignKey("RaceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.SystemModel", "System")
                        .WithMany("SystemRaces")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceGroup");

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemSkillGroup", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Groups.SkillGroup", "SkillGroup")
                        .WithMany()
                        .HasForeignKey("SkillGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.SystemModel", "System")
                        .WithMany("SystemSkills")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillGroup");

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemSpellGroup", b =>
                {
                    b.HasOne("Api.Models.Gameplay.Groups.SpellGroup", "SpellGroup")
                        .WithMany()
                        .HasForeignKey("SpellGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Gameplay.SystemModel", "System")
                        .WithMany("SystemSpells")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpellGroup");

                    b.Navigation("System");
                });

            modelBuilder.Entity("Api.Models.Campaign", b =>
                {
                    b.Navigation("CampaignMembers");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheet", b =>
                {
                    b.Navigation("KnownSkills");

                    b.Navigation("KnownSpells");
                });

            modelBuilder.Entity("Api.Models.Gameplay.CharacterSheetModel", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Currency", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.ClassGroup", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.ItemGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.MapGroup", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.RaceGroup", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.SkillGroup", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Groups.SpellGroup", b =>
                {
                    b.Navigation("Spells");
                });

            modelBuilder.Entity("Api.Models.Gameplay.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Api.Models.Gameplay.SystemModel", b =>
                {
                    b.Navigation("SystemItems");

                    b.Navigation("SystemMaps");

                    b.Navigation("SystemRaces");

                    b.Navigation("SystemSkills");

                    b.Navigation("SystemSpells");
                });
#pragma warning restore 612, 618
        }
    }
}
