services:
  db:
    image: mysql:8.0
    container_name: d-infinity-db
    networks:
      - d-infinity-net
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_infinity
      MYSQL_DATABASE: d_infinity_db
      MYSQL_USER: dm
      MYSQL_PASSWORD: dm
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend/Api
    container_name: d-infinity-back
    networks:
      - d-infinity-net
    volumes:
      - ./backend/Api:/app
      - /app/bin
      - /app/obj
      - ~/.nuget/packages:/root/.nuget/packages
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=d_infinity_db;Uid=root;Pwd=db_infinity;
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: d-infinity-front
    networks:
      - d-infinity-net
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    ports:
      - "4200:4000"

volumes:
  db_data:

networks:
  d-infinity-net:
    driver: bridge